// Auto-generated by strava_segment_analyzer.py
var SEGMENT_REPORTS = [
  {'id': 3591075, 'name': '"G318 Longquan Climb": from \'Y\' intersection to top of the mountain', 'file': 'segment_3591075_analysis.html'},
  {'id': 33862358, 'name': '成都绕城绿道0公里出发，逆时针（Yiyi）', 'file': 'segment_33862358_analysis.html'},
];